version: "3.3"

services:
  www:
    user: 0:0
    image: elestio/kbin:${SOFTWARE_VERSION_TAG}
    restart: always
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    ports:
      - 172.17.0.1:3080:80
    volumes:
      - ./storage/caddy_config:/config
      - ./storage/caddy_data:/data
      - ./storage/media:/var/www/kbin/public/media
    environment:
      - SERVER_NAME=:80 # the addresss that the web server binds
      - PHP_FASTCGI_HOST=php:9000 # caddy forward traffic to this host via fastcgi
      - MERCURE_PUBLISHER_JWT_KEY=${MERCURE_JWT_SECRET}
      - MERCURE_SUBSCRIBER_JWT_KEY=${MERCURE_JWT_SECRET}
      - MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET}
    depends_on:
      - php

  php:
    image: elestio/kbin:${SOFTWARE_VERSION_TAG}
    restart: always
    command: php-fpm
    volumes:
      - ./storage/media:/var/www/kbin/public/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  messenger:
    image: elestio/kbin:${SOFTWARE_VERSION_TAG}
    restart: always
    command: bin/console messenger:consume async --time-limit=3600
    volumes:
      - ./storage/caddy_config:/config
      - ./storage/caddy_data:/data
      - ./storage/media:/var/www/kbin/public/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  messenger_ap:
    image: elestio/kbin:${SOFTWARE_VERSION_TAG}
    restart: always
    command: bin/console messenger:consume async_ap --time-limit=3600
    volumes:
      - ./storage/caddy_config:/config
      - ./storage/caddy_data:/data
      - ./storage/media:/var/www/kbin/public/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  redis:
    image: redis:alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./storage/redis:/data

  db:
    image: elestio/postgres:15
    restart: always
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kbin
      - POSTGRES_USER=kbin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=kbin
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./storage/rabbitmq:/var/lib/rabbitmq

  # Add your favorite reverse proxy (e.g nginx) which accept incoming HTTPS
  # traffic and forward to http://www:80
  # nginx:
  #  image: nginx
  #  ports:
  #    - 443:443
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
